### ISSUE TITLE
Hey, when you say mms do you mean mountainside middle school? cause if so

### ISSUE THREAD

**Issue by Lhinger** [liamhtml/PLAYHYDRA#1]
I have coding experience and would like to help you. idk who you are and your prob in highschool at this point but still

**Comment by Lhinger** [comment]
i take that back, this is recent.

**Comment by Lhinger** [comment]
also, I doubt you mean mountainside middle school cause there are very few smart people here and if you were this smart and knew how to program then I would probably know you. Also, you live in Michigan, and thats not even close to my school so no lol. I feel stupid, have a nice day.

**Comment by liamhtml** [comment]
Hi!
Sorry, I don't go to Mountainside Middle School, but it would still be awesome if you contributed!

**Comment by Lhinger** [comment]
lol i fugured that out, ill try and contribute some stuff

**Comment by liamhtml** [comment]
@Lhinger uhh you can't delete these

"mountainside" is a pretty generic name though, and it looks like there are multiple of them. i wouldn't sweat it too much.

**Comment by liamhtml** [comment]
wait nvm i can
