### ISSUE TITLE
Maybe add a "deploy to heroku" button 

### ISSUE THREAD

**Issue by Lhinger** [liamhtml/PLAYHYDRA#3]
Maybe add a "deploy to Heroku" button so anyone can make their own site in case yours is blocked.

Link to heroku: https://www.heroku.com/

How to deploy a git repo to heroku: https://devcenter.heroku.com/articles/git

Link to some deploy buttons: https://github.com/BinBashBanana/deploy-buttons

When adding the deploy button make sure it directs you to this site: "https://heroku.com/deploy/?template=https://github.com/{user}/{repository}"

**Comment by liamhtml** [comment]
yeah, that's a good idea. heroku is blocked at my school but it would probably work for others.
